#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#author:         rex
#blog:           http://iregex.org
#filename        fullpath.py
#created:        2011-04-07 10:23

import sys
import os
import re
path=os.path.abspath(sys.argv[0])
path='/'.join(path.split('/')[:-1])
print path
